### ISSUE TITLE
problem with Installation

### ISSUE THREAD

**Issue by KsanaE-0** [bikenik/alfred-anki#6]
Hi Bikenik, 
thank you for developing this amazing alfred workflow. I can't wait to use it to create cards. Unfortunately, I came up with trouble with installation of it. I would be grateful it you can help me out or give me a pointer. Thank you!

----

```shell
simon@mac:~$ --> npm -v
6.12.0
simon@mac:~$ --> node -v
v10.16.3
simon@mac:~$ --> sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15
BuildVersion:	19A583
```
```shell
simon@mac:~$ --> sudo npm install --global alfred-anki
Password:

> alfred-anki@1.3.1 postinstall /usr/local/lib/node_modules/alfred-anki
> alfy-init

{ Error: Command failed with exit code 1 (EPERM): alfred-link
    at makeError (/usr/local/lib/node_modules/alfred-anki/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/usr/local/lib/node_modules/alfred-anki/node_modules/execa/index.js:112:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  command: 'alfred-link',
  exitCode: 1,
  exitCodeName: 'EPERM',
  stdout: '',
  stderr:
   'Error: Permission denied to read Alfred preferences at location /Users/simon/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n    at module.exports (/usr/local/lib/node_modules/alfred-anki/node_modules/resolve-alfred-prefs/index.js:44:9)',
  all:
   'Error: Permission denied to read Alfred preferences at location /Users/simonn/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n    at module.exports (/usr/local/lib/node_modules/alfred-anki/node_modules/resolve-alfred-prefs/index.js:44:9)',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  signal: undefined }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! alfred-anki@1.3.1 postinstall: `alfy-init`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the alfred-anki@1.3.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/simon/.npm/_logs/2019-10-13T11_56_36_791Z-debug.log
```
![image](https://user-images.githubusercontent.com/24473107/66715338-7e4e2680-edc2-11e9-9433-b427a784ea97.png)

**Comment by KsanaE-0** [comment]
I've solve this problem by following instructions of this page → [Resolving EACCES permissions errors when installing packages globally](https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally). 

```shell
xxx@mac:~/.npm-global/lib/node_modules$ --> npm install --global alfred-anki

> alfred-anki@1.3.1 postinstall /Users/xxx/.npm-global/lib/node_modules/alfred-anki
> alfy-init

+ alfred-anki@1.3.1
added 258 packages from 395 contributors and updated 3 packages in 10.502s
```

The Installation went smoothly, however this workflow still didn't work on my machine.

Doesn't Anyone have some Ideas?

![image](https://user-images.githubusercontent.com/24473107/66718461-828b3b80-ede4-11e9-90f3-91f063230af2.png)

![image](https://user-images.githubusercontent.com/24473107/66718473-b1091680-ede4-11e9-9021-3a26af930841.png)

**Comment by bikenik** [comment]
Please, try this release and install as [anki.alfredworkflow
](https://github.com/bikenik/alfred-anki/releases/tag/v1.3.1)

**Comment by KsanaE-0** [comment]
It works! Thank you very much!
